version: '3.8'

services:
  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - hostname=rabbit-service
      - name=rabbit
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  postgres:
    image: postgres:16.0
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=parserdb
      - POSTGRES_HOST_AUTH_METHOD=trust
  postgres-web:
    image: adminer:4.8.1
    ports:
      - 8082:8080
  